### ISSUE TITLE
Request for Adafruit Pro Trinket LiIon/LiPoly Backpack Add-On Eagle files

### ISSUE THREAD

**Issue by rboyd** [adafruit/Adafruit-Pro-Trinket-PCBs#1]
Any chance we get the battery backpack too?
http://www.adafruit.com/products/2124

**Comment by ladyada** [comment]
Hiya its here
https://github.com/adafruit/Adafruit-MicroLipo-PCB!

**Comment by seanahrens** [comment]
Sweet thanks @ladyada !
